repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
            examples/nbconverted/.*|
            examples/nbconvert/.*|
            .*\.ipynb$
          )

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.0
  hooks:
    - id: ruff-check
      types_or: [python, pyi]
      args: [--fix, --line-length=100]
      # Only lint src/ and tests/
      files: |
        (?x)^(
          utils/|
          src/|
          tests/
        )
      # and ignore ipynb-generated Python files if needed:
      exclude: |
        (?x)^(
          examples/.*|
          .*nbconvert.*|
          .*nbconverted.*|
          .*\.ipynb$
        )
    - id: ruff-format
      types_or: [python, pyi]
      args: [--line-length=100]
      files: |
        (?x)^(
          utils/|
          src/|
          tests/
        )
      exclude: |
        (?x)^(
          examples/.*|
          .*nbconvert.*|
          .*nbconverted.*|
          .*\.ipynb$
        )
