analysis_out_dir: /PATH/TO/HOUSE/INTERMEDIATE/IMAGE/OUTPUTS/
local_image_dir: /PATH/TO/LOCAL/IMAGES/
local_profile_dir: /PATH/TO/LOCAL/PROFILES/
channels: [OrigER, OrigRNA, OrigAGP, OrigMito, OrigDNA, OrigBrightfield]
input_channel: OrigBrightfield
path_col_prefix: "PathName_"
file_col_prefix: "FileName_"
# original analysis data root path, shouldn't change since the loaddata are downloaded from a pinned commit
source_path_prefix: "/media/18tbdrive" 
simulation_subsample_n: 50 # max number of crops to sample per well/plate combination for metric evaluation
simulation_subsample_seed: 42
