"""
Helper utility for filtering virtual_stain_flow.datasets.ds_engine.crop_generators
    .generate_tile_crops (https://github.com/WayScience/virtual_stain_flow.git)
    output against object center mappings to only retain patches that contains
    at least one object center within the crop.
"""

from collections.abc import Mapping, Sequence
from typing import TypeAlias

CropSpec: TypeAlias = tuple[tuple[int, int], int, int]
PointMapping: TypeAlias = Mapping[str, Sequence[float]]


def filter_crops_with_objects(
    crop_specs: Mapping[int, Sequence[CropSpec]],
    pt_mapping: Sequence[PointMapping],
) -> dict[int, list[CropSpec]]:
    """
    Helper utility for filtering virtual_stain_flow tiling crops generated by
    `generate_tile_crops` to only retain those that contain at least one object center.

    :params crop_specs: Mapping from image index to a sequence of crop specifications.
        Should be the raw output of `generate_tile_crops`.
    :params pt_mapping: Sequence of point mappings for each image.
        Should be the raw output of the object center mappings for each image,
        from /utils/loaddata_to_index.build_dataset_inputs function.
    :returns: Dictionary mapping image index to a list of filtered crop specifications.
        Has the exact same structure as the input `crop_specs` mapping, just
        with only the crops that contain at least one object center.
    """
    filtered_specs: dict[int, list[CropSpec]] = {}

    for image_index, image_crop_specs in crop_specs.items():
        try:
            points = pt_mapping[image_index]
            x_coordinates = points["X"]
            y_coordinates = points["Y"]
        except (IndexError, KeyError) as error:
            raise ValueError(
                f"No X/Y point mapping found for image index {image_index}."
            ) from error

        if len(x_coordinates) != len(y_coordinates):
            raise ValueError(
                f"X/Y coordinate counts differ for image index {image_index}."
            )

        filtered_specs[image_index] = [
            ((crop_x, crop_y), width, height)
            for (crop_x, crop_y), width, height in image_crop_specs
            if any(
                crop_x <= object_x < crop_x + width
                and crop_y <= object_y < crop_y + height
                for object_x, object_y in zip(x_coordinates, y_coordinates)
            )
        ]

    return filtered_specs
